# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [10]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [11]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.49799463 0.09221673 0.12012229 ... 0.9857974  0.60478586 0.27264523]
 [0.71503676 0.51440121 0.45824151 ... 0.55851078 0.98940144 0.0306147 ]
 [0.1722417  0.22777135 0.62945501 ... 0.09020327 0.79683097 0.32049318]
 ...
 [0.6005433  0.44173842 0.70795172 ... 0.34185273 0.12967368 0.38667553]
 [0.41309735 0.2977195  0.2139318  ... 0.82333605 0.20577767 0.16309415]
 [0.61748721 0.81741988 0.6846291  ... 0.26741392 0.81544501 0.28174852]]
[[0.39646322 0.80429183 0.37128787 ... 0.1396542  0.78039839 0.81515304]
 [0.29616746 0.22327388 0.11195768 ... 0.1290761  0.36237747 0.8766168 ]
 [0.17671148 0.9692845  0.68178288 ... 0.33160645 0.88305488 0.10250286]
 ...
 [0.70983796 0.63687614 0.01729475 ... 0.41945533 0.0170853  0.53464465]
 [0.35385423 0.31746284 0.69934549 ... 0.9933044  0.23947503 0.9828641 ]
 [0.25412765 0.23787226 0.25748183 ... 0.18467509 0.60503358 0.18842029]]


Без использования numpy

In [12]:
def mult(a, b):
    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [13]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [14]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 735 ms, sys: 2.12 ms, total: 737 ms
Wall time: 738 ms


In [15]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.01 ms, sys: 177 µs, total: 2.19 ms
Wall time: 6.26 ms


In [16]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5274892462002754e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [24]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.70259326 0.6061658  0.55664323] [0.03600484 0.89721716 0.45874709]


In [27]:
def scalar_product(a,b):
    s = sum(x * y for x,y in zip(a, b))
    return s

In [28]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [37]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

0.824517584851638
CPU times: user 1.95 ms, sys: 0 ns, total: 1.95 ms
Wall time: 1.84 ms
0.824517584851638
CPU times: user 587 µs, sys: 0 ns, total: 587 µs
Wall time: 914 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** NumPy обеспечивает высокую производительность благодаря реализации на C/C++, векторизации операций и оптимизированным алгоритмам

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [44]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    size = a.shape[0]
    diagonal1 = np.diagonal(a)
    diagonal2 = np.diagonal(np.fliplr(a))
    result = sum(diagonal1[diagonal1 % 2 == 0]) + sum(diagonal2[diagonal2 % 2 == 0])

    if size % 2 == 1:
        center_element = a[size // 2, size // 2]
        if center_element % 2 == 0:
            result -= center_element
    return result

In [45]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 7, 9, 3, 4],
       [9, 3, 3, 8, 4],
       [5, 8, 6, 8, 6],
       [9, 6, 5, 5, 9],
       [9, 8, 1, 9, 3]])

In [56]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 237 µs, sys: 0 ns, total: 237 µs
Wall time: 245 µs


24

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [47]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    cumsum = np.cumsum(a, axis=1)
    row_indexes = np.arange(1, a.shape[1] + 1)
    result = cumsum / row_indexes
    return result

In [55]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[9.29479446e-01 1.78009483e-02 1.99657404e-01 7.77947161e-02
 4.24359848e-01 6.87177576e-01 4.54402521e-01 3.60177637e-01
 1.11794834e-01 9.90320274e-01 3.91282138e-01 5.16840096e-01
 4.74850582e-01 3.00594228e-01 5.50667330e-01 3.76482396e-01
 2.79378048e-01 1.00598871e-02 6.48722204e-01 4.22986954e-01
 2.72198976e-01 5.72728340e-01 8.97082816e-01 4.74158804e-01
 6.39909756e-01 5.75059172e-01 5.39407551e-01 9.35415785e-01
 2.32382756e-01 2.03882820e-01 5.36086864e-01 1.20234311e-01
 4.73783077e-01 2.72412778e-01 6.78339931e-01 6.13480840e-01
 9.90643725e-02 5.60950451e-01 2.27624528e-01 2.40204237e-01
 1.85911579e-01 7.17123755e-01 4.70319901e-01 5.66922921e-01
 1.84315975e-01 8.48278527e-01 6.40274690e-01 4.86594333e-01
 9.01725923e-01 7.33718831e-01 4.40344041e-02 9.64504049e-01
 1.61498394e-01 3.42626613e-01 2.65842266e-01 1.69832704e-01
 1.13774161e-01 5.13332721e-01 7.98067226e-01 1.99636918e-01
 1.71623613e-01 1.49351054e-01 6.12066064e-01 2.79244766e-01
 2.11183683e-01 4.458630

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [53]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    unique_elements_indexes = np.where(np.diff(a) != 0)[0] + 1
    unique_elements_arrays = np.split(a, unique_elements_indexes)

    unique_elements = np.array([subarray[0] for subarray in unique_elements_arrays])
    counts = np.array([len(subarray) for subarray in unique_elements_arrays])
    return unique_elements, counts

In [54]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 174 µs, sys: 24 µs, total: 198 µs
Wall time: 204 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [58]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """

    arrays_copy = X.copy()
    arrays_copy[1::2] = a
    arrays_copy[0::2] **= 3
    new_array = arrays_copy[::-1]
    result = np.concatenate([X, new_array])
    return result

In [62]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 798 µs, sys: 0 ns, total: 798 µs
Wall time: 806 µs
